import {
  FaReact,
  FaPython,
  FaDocker,
  FaJava,
  FaGoogle,
  FaDatabase,
  FaCog,
  FaServer,
  FaLinux,
  FaMicrochip,
} from 'react-icons/fa';
import {
  SiNextdotjs,
  SiTypescript,
  SiFirebase,
  SiMongodb,
  SiCplusplus,
  SiC,
  SiGo,
  SiPostman,
  SiElectron,
  SiSqlite,
  SiPytorch,
  SiTensorflow,
  SiScikitlearn,
  SiPandas,
  SiNumpy,
  SiReact,
  SiThreedotjs,
  SiFlask,
  SiOpenai,
  SiAnthropic,
  SiArm,
} from 'react-icons/si';
import {DiJavascript1} from 'react-icons/di';

import PlaywrightIcon from './PlaywrightIcon';

export const techIconMap = {
  React: <FaReact color="#61DAFB" />,
  'Next.js': <SiNextdotjs color="#000000" />,
  TypeScript: <SiTypescript color="#3178C6" />,
  Firebase: <SiFirebase color="#FFCA28" />,
  MongoDB: <SiMongodb color="#47A248" />,
  Go: <SiGo color="#00ADD8" />,
  Python: <FaPython color="#3776AB" />,
  'C++': <SiCplusplus color="#00599C" />,
  C: <SiC color="#A8B9CC" />,
  Linux: <FaLinux color="#FCC624" />,
  Docker: <FaDocker color="#2496ED" />,
  gRPC: <FaServer color="#4285F4" />,
  Java: <FaJava color="#ED8B00" />,
  JSP: <FaJava color="#ED8B00" />,
  SQL: <FaDatabase color="#336791" />,
  Playwright: <PlaywrightIcon color="#2EAD33" />,
  Postman: <SiPostman color="#FF6C37" />,
  GDB: <FaCog color="#FF6C37" />,
  Valgrind: <FaCog color="#FF6C37" />,
  'Google Cloud (GCP)': <FaGoogle color="#4285F4" />,
  BigQuery: <FaDatabase color="#4285F4" />,
  JavaScript: <DiJavascript1 color="#F7DF1E" />,
  Electron: <SiElectron color="#47848F" />,
  SQLite3: <SiSqlite color="#003B57" />,
  'HTML/CSS': <DiJavascript1 color="#F7DF1E" />,
  PyTorch: <SiPytorch color="#EE4C2C" />,
  Numpy: <SiNumpy color="#4DABCF" />,
  Tensorflow: <SiTensorflow color="#FF6F00" />,
  Matplotlib: <FaPython color="#3776AB" />,
  'Scikit-learn': <SiScikitlearn color="#F7931E" />,
  Pandas: <SiPandas color="#130654" />,
  'React Native': <SiReact color="#61DAFB" />,
  'OpenAI API': <SiOpenai color="#10A37F" />,
  'Claude API': <SiAnthropic color="#10A37F" />,
  argparse: <FaPython color="#3776AB" />,
  Loma: <FaPython color="#3776AB" />,
  'Three.js': <SiThreedotjs color="#000000" />,
  Flask: <SiFlask color="#000000" />,
  Scapy: <FaPython color="#3776AB" />,
  'RIPE Atlas API': <FaDatabase color="#336791" />,
  ARM: <SiArm color="#0091BD" />,
  Assembly: <FaMicrochip color="#6E6E6E" />,
  PIL: <FaPython color="#3776AB" />,
};
