name: Pull Request Checks

on:
  pull_request:
    branches: ["main"]

jobs:
  # Security scan job
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Dependency Review
        uses: actions/dependency-review-action@v4
